name: Expresion

on:
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: number
      nombre:
        description: 'Nombre'
        required: true
        default: 'Valor default'
        type: string
  push:
    branches: ["main"]
  issues:
    types: 
      - closed
      - opened
      
jobs:
  tipo-issue:
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es mayor de edad
      - name: Mostrar nombre de evento
        run: echo ${{ github.event_name }}
      - name: Mostrar nombre de usuario
        run: echo ${{ github.actor }}
      - name: Mostrar repositorio
        run: echo ${{github.repository }}
      - name: Mostrar rama actual
        run: echo ${{github.ref}}
      - id: obtener_version
        run: echo "version=1.0.0" >> $GITHUB_OUTPUT
      - name: Mostrar version
        run: echo "Versión "${{ steps.obtener_version }}
  mayor:
    if: ${{ inputs.edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es mayor de edad
      - name: Mostrar nombre de evento
        run: echo ${{ github.event_name }}
      - name: Mostrar nombre de usuario
        run: echo ${{ github.actor }}
      - name: Mostrar repositorio
        run: echo ${{github.repository }}
      - name: Mostrar rama actual
        run: echo ${{github.ref}}
      - name: Mostrar secret
        run: echo Secrets - ${{secrets.PASSWORD}}
  menor:
    if: ${{ inputs.edad < 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es menor de edad
